from __future__ import annotations

"""
DocMind Second Brain — Retention Flashcards Strategy
Generates high-retention front/back flashcards for active recall.
"""

from typing import List
from backend.output.strategies.base import DeliverableStrategy


class FlashcardsStrategy(DeliverableStrategy):
    @property
    def deliverable_type(self) -> str:
        return "FLASHCARDS"

    @property
    def default_subdir(self) -> str:
        return "notes"

    def build_instruction(self, topic: str) -> str:
        return (
            f"Create 4 high-retention Flashcards on '{topic}'.\n"
            "Format each flashcard as:\n"
            "### Flashcard [Number]: [Concept Name]\n"
            "- **Front (Question / Prompt)**: [Targeted active-recall question]\n"
            "- **Back (Answer & Key Nuance)**: [Concise answer and core mechanism]\n"
            "- **Citation**: [Document source and page]\n"
        )

    def format_offline_content(
        self,
        topic: str,
        chunks: List[str],
        source_labels: List[str],
    ) -> str:
        cards = []
        for i, chk in enumerate(chunks[:4], start=1):
            cite = source_labels[i - 1] if i - 1 < len(source_labels) else "Course Context"
            first_line = chk.strip().split("\n")[0][:80]
            cards.append(
                f"### Flashcard {i}: {topic} (Key Concept {i})\n"
                f"- **Front (Question / Prompt)**: What is the core function described regarding {first_line}?\n"
                f"- **Back (Answer & Nuance)**: {chk[:200].strip()}...\n"
                f"- **Citation**: {cite}\n"
            )
        return (
            f"# {topic} — Active Recall Flashcards\n\n"
            f"*Generated by DocMind Second Brain*\n\n"
            + "\n".join(cards)
        )
