from __future__ import annotations

"""
DocMind Second Brain — Practice Quiz Strategy
Generates 5-question multiple choice quizzes with answer keys and citations.
"""

from typing import List
from backend.output.strategies.base import DeliverableStrategy


class QuizStrategy(DeliverableStrategy):
    @property
    def deliverable_type(self) -> str:
        return "QUIZ"

    @property
    def default_subdir(self) -> str:
        return "quizzes"

    def build_instruction(self, topic: str) -> str:
        return (
            f"Generate a 5-Question Practice Exam Quiz on '{topic}'.\n"
            "Format each question as:\n"
            "### Question [Number]: [Clear question statement]\n"
            "- A) [Option]\n"
            "- B) [Option]\n"
            "- C) [Option]\n"
            "- D) [Option]\n"
            "- **Answer & Explanation**: [Correct option] - [Explanation citing specific document/page]\n\n"
            "Base all questions strictly on facts from the context."
        )

    def format_offline_content(
        self,
        topic: str,
        chunks: List[str],
        source_labels: List[str],
    ) -> str:
        sample_cite = source_labels[0] if source_labels else "Uploaded Document"
        first_chunk = chunks[0][:150].replace("\n", " ") if chunks else topic
        return (
            f"# {topic} — Practice Quiz & Assessment\n\n"
            f"*Generated by DocMind Second Brain*\n\n"
            f"### Question 1\n"
            f"Based on the course documents, which statement accurately reflects: '{first_chunk}...'?\n\n"
            f"- A) It is an obsolete mechanism.\n"
            f"- B) It provides the foundational definition described in the text.\n"
            f"- C) It contradicts standard documentation.\n"
            f"- D) None of the above.\n\n"
            f"**Answer**: **B** — Verified directly from {sample_cite}.\n"
        )
