from __future__ import annotations

"""
DocMind Second Brain — Study Notes Deliverable Strategy
Generates high-yield study guides and cheat sheets.
"""

from typing import List
from backend.output.strategies.base import DeliverableStrategy


class StudyNotesStrategy(DeliverableStrategy):
    @property
    def deliverable_type(self) -> str:
        return "STUDY_NOTES"

    @property
    def default_subdir(self) -> str:
        return "notes"

    def build_instruction(self, topic: str) -> str:
        return (
            f"Create a high-yield Study Guide & Concept Cheat Sheet on '{topic}'.\n"
            "Structure:\n"
            "1. 🎯 Executive Overview & Core Definition\n"
            "2. 🔑 Key Concepts & Mechanisms (with bullet points)\n"
            "3. 📊 Comparison / Breakdown Table\n"
            "4. ⚠️ Common Pitfalls & Exam Traps\n"
            "5. 📎 Grounded Source Citations\n"
            "Base your notes strictly on the provided study context."
        )

    def format_offline_content(
        self,
        topic: str,
        chunks: List[str],
        source_labels: List[str],
    ) -> str:
        snippet_blocks = "\n\n".join([f"> {c[:240]}..." for c in chunks[:3]])
        citations = "\n".join([f"- {s}" for s in source_labels])
        return (
            f"# {topic} — Study Notes & Cheat Sheet\n\n"
            f"*Generated by DocMind Second Brain (Offline Synthesis)*\n\n"
            f"## 🎯 Overview & Context\n"
            f"Synthesized from {len(chunks)} verified document passages.\n\n"
            f"### Key Knowledge Passages\n{snippet_blocks}\n\n"
            f"### 📎 Verified Citations\n{citations}\n"
        )
