from __future__ import annotations

"""
DocMind Second Brain — Executive Summary Strategy
Generates concise takeaways, architectural summaries, and grounded citations.
"""

from typing import List
from backend.output.strategies.base import DeliverableStrategy


class SummaryStrategy(DeliverableStrategy):
    @property
    def deliverable_type(self) -> str:
        return "SUMMARY"

    @property
    def default_subdir(self) -> str:
        return "summaries"

    def build_instruction(self, topic: str) -> str:
        return (
            f"Write a concise executive summary on '{topic}'.\n"
            "Include high-level architectural takeaways, core principles, practical implications, and cite specific pages."
        )

    def format_offline_content(
        self,
        topic: str,
        chunks: List[str],
        source_labels: List[str],
    ) -> str:
        snippet_blocks = "\n\n".join([f"- {c[:220]}..." for c in chunks[:3]])
        citations = "\n".join([f"- {s}" for s in source_labels])
        return (
            f"# {topic} — Executive Summary\n\n"
            f"*Generated by DocMind Second Brain*\n\n"
            f"## Executive Overview\n"
            f"Ground-truth digest compiled from {len(chunks)} document excerpts.\n\n"
            f"### Key Findings\n{snippet_blocks}\n\n"
            f"### Document References\n{citations}\n"
        )
