from __future__ import annotations

"""
DocMind Second Brain — Outputs REST API Router
Endpoints for generating and retrieving structured study deliverables (Notes, Summaries, Quizzes).
"""

from typing import List, Optional, Union
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel
from backend.database.crud import list_outputs
from backend.database.models import OutputArtifactModel
from backend.output.generator import generate_study_deliverable

router = APIRouter(prefix="/outputs", tags=["Outputs"])


class GenerateOutputRequest(BaseModel):
    topic: Optional[str] = None
    title: Optional[str] = None
    output_type: Optional[str] = None
    deliverable_type: Optional[str] = None  # notes, summary, quiz, flashcards
    folder_scope: Optional[Union[List[str], str]] = None
    folder: Optional[str] = None
    doc_id: Optional[str] = None
    notes: Optional[str] = None
    user_id: str = "default_user"
    max_tokens: int = 768


@router.get("", response_model=List[OutputArtifactModel])
def get_outputs(user_id: str = "default_user", output_type: Optional[str] = None):
    """Lists all saved deliverables generated by DocMind."""
    return list_outputs(user_id=user_id, output_type=output_type)


@router.post("/generate", status_code=status.HTTP_201_CREATED)
def generate_output_endpoint(req: GenerateOutputRequest):
    """
    Synthesizes a structured study deliverable based on uploaded document evidence.
    Saves markdown to output/ and registers the artifact in SQLite.
    """
    # 1. Resolve topic
    topic = req.topic or req.title or ""
    if not topic.strip():
        if req.doc_id:
            from backend.database.crud import get_document_by_id
            doc = get_document_by_id(req.doc_id)
            if doc:
                topic = doc.filename
        if not topic.strip():
            topic = "Core Document Concepts"

    # 2. Map deliverable type
    raw_type = req.output_type or req.deliverable_type or "STUDY_NOTES"
    type_map = {
        "notes": "STUDY_NOTES",
        "study_notes": "STUDY_NOTES",
        "summary": "SUMMARY",
        "quiz": "QUIZ",
        "flashcards": "FLASHCARDS",
    }
    norm_type = type_map.get(raw_type.lower(), raw_type.upper())

    # 3. Resolve folder scope
    folder_raw = req.folder_scope or req.folder
    effective_folders = None
    if folder_raw and folder_raw != "All" and folder_raw != "All Collections":
        effective_folders = [folder_raw] if isinstance(folder_raw, str) else folder_raw

    res = generate_study_deliverable(
        topic=topic,
        output_type=norm_type,
        folder_scope=effective_folders,
        user_id=req.user_id,
        max_tokens=req.max_tokens,
    )

    if not res.get("success", False):
        raise HTTPException(status_code=422, detail=res.get("error", "Failed to generate artifact."))

    return res
